### ISSUE TITLE
One bug in executing addi.

### ISSUE THREAD

**Issue by TuoBaed** [siriusdemon/Rare#1]
``` rust
let imm = ((inst & 0xfff0_0000) as i64 >> 20) as u64;
```
Above is a bug. Variable inst is u32 type but when you want to get its most significant 12 bits and sign-extended, you should use following code: 
``` rust
let imm = ((inst & 0xfff0_0000) as i32 as i64 >> 20) as u64;
```
because if you don't use as i32 first, rust will convert **(inst & 0xfff0_0000)** as u64 first and the convert it as i64. Try -2048 as your imm and you will see this bug.

**Comment by siriusdemon** [comment]
You are right! Thank you! I have fixed it.
